README.md
runner/sample-problems/sample_lp.lp
runner/sample-problems/sample_mip.lp

- **Linopy Version**: Using the latest master branch. 
- **Test Cases**: Evaluated with two sample problems:
- runner/sample-problems/sample_lp.lp
- runner/sample-problems/sample_mip.lp
**Benchmark Results**
| Benchmark   | Solver | Status | Termination Condition | Objective Value | Runtime (s)       | Memory Usage (MB) |
|-------------|--------|--------|-----------------------|-----------------|-------------------|--------------------|
| sample_lp   | gurobi | ok     | optimal               | 11.75           | 0.0040            | 162.264            |
| sample_lp   | highs  | ok     | optimal               | 11.75           | 0.0024            | 158.212            |
| sample_lp   | glpk   | ok     | optimal               | 11.75           | 0.0092            | 157.996            |
| …

Runner: use master branch of linopy

---

website/compare.py
website/components/filter.py
website/history.py
website/home.py
website/raw-results.py
website/scaling.py
website/utils/filters.py

Website: add size filters

---

website/compare.py
website/components/compare_chart.py

Add support for solver version selection on the comparison page

---

Dockerfile
README.md

- How to run
```bash
docker build -t website-with-gurobi-results .
docker run -p 8501:8501 website-with-gurobi-results
```
- Save the Image as a .tar File
```
docker save -o website-with-gurobi-results.tar website-with-gurobi-results
```
- Instructions to Load and Run
```
docker load < website-with-gurobi-results.tar
```
- Run the Docker container:
```
docker run -p 8501:8501 website-with-gurobi-results
```

Add Dockerfile for Website

---

benchmarks/jump_highs_platform/Metadata_powermodels.yaml

Hi @siddharth-krishna , I opened this new PR to update MILP features on PowerModels metadata

update MILP features for PowerModels benchmarks

---

benchmarks/jump_highs_platform/Metadata_genx.yaml
benchmarks/jump_highs_platform/Metadata_sienna.yaml
benchmarks/pypsa/metadata.yaml
results/metadata.yaml

Hi @siddharth-krishna , I made corrections to some PyPSA metadata

Benchmarks: correct metadata for some MILPs

---

benchmarks/times/metadata.yaml
results/metadata.yaml

Adding TIMES-GEO benchmarks provided by Maurizio here :) should be real-size problems, they tested them with CPLEX and they were solved in 40-50 minutes

Benchmarks: add TIMES-GEO benchmarks

---

runner/run_benchmarks.py
runner/run_solver.py

See the discussion in RFC issue #159

Runner: use perf_counter and add reported runtimes

---

website-nextjs/src/components/admin/solvers/SolverSection.tsx
website-nextjs/src/components/landing-page/sections/MainContentSection.tsx
website-nextjs/src/components/shared/D3PlotChart.tsx
website-nextjs/src/components/shared/PerformanceBarChart.tsx
website-nextjs/src/types/benchmark.ts

Website: Relative performance plot (TOs and other errors)

---

website-nextjs/src/components/admin/FilterSection.tsx

Website: Refactor FilterSection to remove unnecessary max-height style

---

website-nextjs/src/components/admin/benchmark-detail/BenchmarksSection.tsx
website-nextjs/src/components/shared/D3PlotChart.tsx
website-nextjs/src/components/shared/PerformanceBarChart.tsx
website-nextjs/src/types/benchmark.ts

Issue: https://github.com/open-energy-transition/solver-benchmark/issues/213

Error plotting improvements

---

website-nextjs/src/components/admin/compare-solvers/ChartCompare.tsx
website-nextjs/src/components/admin/compare-solvers/SolverSelection.tsx
website-nextjs/src/utils/chart.ts

Website: Log scale Compare Solvers plots

---

website-nextjs/src/components/admin/FilterSection.tsx
website-nextjs/src/components/admin/benchmark-detail/BenchmarkDetailFilterSection.tsx
website-nextjs/src/components/admin/home/BenchmarkSet.tsx
website-nextjs/src/pages/_app.tsx
website-nextjs/src/pages/dashboard/benchmark-set.tsx
website-nextjs/src/pages/dashboard/benchmark-summary.tsx
website-nextjs/src/redux/filters/actions.ts
website-nextjs/src/redux/filters/reducer.ts
website-nextjs/src/types/benchmark.ts
website-nextjs/src/types/state.ts

Website: Replace Model filter with Modelling framework filter

---

website-nextjs/src/components/admin/benchmark-detail/SolverRuntimeComparison.tsx
website-nextjs/src/components/shared/D3GroupedBarChart.tsx

Fixes: https://github.com/open-energy-transition/solver-benchmark/issues/249

Website: runtime plots improvements

---

website-nextjs/src/components/key-insights/charts/ProblemClassTable.tsx

Fixes https://github.com/open-energy-transition/solver-benchmark/issues/254

Website: Improve open source feasibility section

---

website-nextjs/src/components/info-pages/ContentSection.tsx
website-nextjs/src/components/info-pages/PageLayout.tsx
website-nextjs/src/components/info-pages/TableOfContents.tsx
website-nextjs/src/components/info-pages/index.ts
website-nextjs/src/components/landing-page/sections/HowDoWeBenchmarkSection.tsx
website-nextjs/src/components/landing-page/sections/MainContentSection.tsx
website-nextjs/src/components/shared/Header.tsx
website-nextjs/src/constants/path.ts
website-nextjs/src/hooks/index.ts
website-nextjs/src/hooks/useHash.ts
website-nextjs/src/pages/key-insights.tsx
website-nextjs/src/pages/methodology.tsx
website-nextjs/src/styles/globals.css

Fixes: https://github.com/open-energy-transition/solver-benchmark/issues/204

Website: add Methodology page

---

website-nextjs/src/components/admin/benchmark-detail/SolverRuntimeComparison.tsx
website-nextjs/src/components/info-pages/TableOfContents.tsx
website-nextjs/src/components/key-insights/FactorsAffectingPerformanceInsights.tsx
website-nextjs/src/components/key-insights/RuntimeComparison.tsx
website-nextjs/src/components/key-insights/charts/BenchmarkRuntimeComparison.tsx
website-nextjs/src/components/key-insights/charts/RealisticRuntimeComparison.tsx
website-nextjs/src/components/key-insights/charts/factors-affecting-performance/D3PlotChartPerformanceScalling.tsx
website-nextjs/src/components/key-insights/charts/factors-affecting-performance/PerformanceScalling.tsx
website-nextjs/src/components/key-insights/charts/factors-affecting-performance/RuntimeOfFastestSolver.tsx
website-nextjs/src/components/shared/D3GroupedBarChart.tsx
website-nextjs/src/pages/dashboard/main-result/SgmRuntimeComparison.tsx
website-nextjs/src/pages/key-insights.tsx
website-nextjs/src/types/chart.ts

Website: Key Insights: factors affecting performance

---

website-nextjs/src/pages/dashboard/main-results.tsx

Fixes: https://github.com/open-energy-transition/solver-benchmark/issues/198

Website: Improve note in the main section

---

website-nextjs/src/components/landing-page/sections/GetStartedSection.tsx

Quick fix to the landing page -- would love a quick review so it can be live before my talk at 8:30am 🙏

Website: fix sentence in Getting Started section

---

website-nextjs/src/components/landing-page/sections/ContributeSection.tsx

Website: Fix text color in contribute section

---

benchmarks/jump_highs_platform/metadata_genx.yaml
results/metadata.yaml

Noticed these typos during the website showcase :) @siddharth-krishna

Benchmarks: Correct short description

---

website-nextjs/src/components/admin/benchmark-detail/BenchmarkTableResult.tsx
website-nextjs/src/components/admin/home/ResultsSgmModeDropdown.tsx
website-nextjs/src/components/admin/raw-result/DebouncedInput.tsx
website-nextjs/src/components/shared/tables/TanStackTable.tsx

related https://github.com/open-energy-transition/solver-benchmark/issues/209 https://github.com/open-energy-transition/solver-benchmark/issues/212

Website: Benchmark Set table improvements

---

website-nextjs/src/components/admin/ConfigurationSection.tsx
website-nextjs/src/components/admin/FilterSection.tsx
website-nextjs/src/components/admin/ResultsSections.tsx
website-nextjs/src/components/admin/benchmark-detail/BenchmarkTableResult.tsx
website-nextjs/src/components/admin/home/BenchmarkSet.tsx
website-nextjs/src/components/admin/home/ResultsSgmModeDropdown.tsx
website-nextjs/src/components/admin/performance-history/SolverEvolutionSection.tsx
website-nextjs/src/components/admin/raw-result/DebouncedInput.tsx
website-nextjs/src/components/info-pages/ContentSection.tsx
website-nextjs/src/components/info-pages/PageLayout.tsx
website-nextjs/src/components/info-pages/TableOfContents.tsx
website-nextjs/src/components/landing-page/sections/MainContentSection.tsx
website-nextjs/src/components/landing-page/sections/MissionStartSection.tsx
website-nextjs/src/components/shared/AdminHeader.tsx
website-nextjs/src/components/shared/ContentWrapper.tsx
website-nextjs/src/components/shared/Header.tsx
website-nextjs/src/components/shared/Navbar.tsx
website-nextjs/src/components/shared/PerformanceBarChart.tsx
website-nextjs/src/components/shared/tables/TanStackTable.tsx
website-nextjs/src/pages/dashboard/benchmark-set.tsx
website-nextjs/src/pages/dashboard/main-results.tsx
website-nextjs/src/styles/globals.css
website-nextjs/tailwind.config.ts

Website: Refactor layout and styling across multiple components
